server:
  port: 8888

spring:
  application:
    name: changgou-eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
    register-with-eureka: false
    fetch-registry: false
