spring:
  application:
    name: changgou-gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
           #商品微服务
        - id: changgou_goods_route
          uri: lb://changgou-service-goods
          predicates:
            - Path=/api/album/**,/api/brand/**,/api/cache/**,/api/categoryBrand/**,/api/category/**,/api/para/**,/api/pref/**,/api/sku/**,/api/spec/**,/api/spu/**,/api/stockBack/**,/api/template/**
          filters:
            - StripPrefix=1
          #用户微服务
        - id: changgou_user_route
          uri: lb://changgou-service-user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
          #认证微服务
        - id: changgou_oauth_user
          uri: lb://changgou-user-auth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
            #订单微服务
        - id: changgou_order_route
          uri: lb://changgou-service-order
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        #购物车页面渲染微服务
        - id: changgou_web_order_route
          uri: lb://changgou-web-order
          predicates:
            - Path=/api/wcart/**,/api/worder/**,/api/pay/**
          filters:
            - StripPrefix=1
        #秒杀微服务
        - id: changgou_seckill_route
          uri: lb://changgou-service-seckill
          predicates:
            - Path=/api/seckillgoods/**
          filters:
            - StripPrefix=1
        #秒杀渲染服务
        - id: changgou_web_seckill_route
          uri: lb://changgou-web-seckill
          predicates:
            - Path=/api/wseckillgoods/**
          filters:
            - StripPrefix=1
  redis:
    host: 192.168.200.128
server:
  port: 8001
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true